### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by asdrabael** [XLabs-AI/deforum-x-flux#3]
I managed to get it running, but got this error:
Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
Traceback (most recent call last):
  File "/home/asdra/Desktop/deforum-x-flux/run.py", line 405, in <module>
    ffmpeg_args_dict = ffmpegArgs()
                       ^^^^^^^^^^^^
  File "/home/asdra/Desktop/deforum-x-flux/run.py", line 85, in ffmpegArgs
    ffmpeg_extension, ffmpeg_maxframes = get_extension_maxframes(args,ffmpeg_outdir,ffmpeg_timestring)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asdra/Desktop/deforum-x-flux/./deforum_flux/helpers/ffmpeg_helpers.py", line 13, in get_extension_maxframes
    extension = all_frames[0].split(".")[-1]
                ~~~~~~~~~~^^^
IndexError: list index out of range

Even though I can run flux normally, for some reason I would get an OOM error so I changed offload to True on line 91 which allowed it to run slowly but it used 12gb vram. To test it, I changed the frames to 50, the steps to 15 but kept everything else the same. 45 min into it, it returned this error with no frames produced at all.

**Comment by unsaid-azizov** [comment]
take a look at outputs dir

**Comment by asdrabael** [comment]
> take a look at outputs dir

I did. It's completely empty other than a text file title with the seed and deforum's settings. nothing else. each attempt makes a text file and that's all.

**Comment by tavyscrolls** [comment]
did you try running "create video from frames" before a frame was done?

**Comment by asdrabael** [comment]
> did you try running "create video from frames" before a frame was done?

No, because that's not an option. I literally start the program and it fails because there's something wrong with it. Meanwhile I can use the experimental Forge Flux deforun easily, and it uses less vram. As far as I can tell, this is just broken or has requirements nor being informed about.
