### ISSUE TITLE
can't run in windows11 with RTX4090

### ISSUE THREAD

**Issue by YuanXiaoYaoZiZai** [XLabs-AI/deforum-x-flux#8]
Ram 24GB is not enough，anything wrong?

**Comment by YuanXiaoYaoZiZai** [comment]
```
(G:\conda\envs_dirs\deforum_xflux) E:\project\deforum-x-flux>  python run.py
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 10.00it/s]
Init model
Loading checkpoint
Start a quantization process...
Traceback (most recent call last):
  File "E:\project\deforum-x-flux\run.py", line 122, in <module>
    root.__dict__.update(ModelSetup())
  File "E:\project\deforum-x-flux\run.py", line 119, in ModelSetup
    model = Model("flux-dev-fp8", quantized=True)
  File "E:\project\deforum-x-flux\run.py", line 92, in __init__
    self.dit, self.ae, self.t5, self.clip = self.get_models(name, 'cuda', offload=False, is_schnell=False, quantized=quantized)
  File "E:\project\deforum-x-flux\run.py", line 98, in get_models
    dit = load_flow_model_quintized("flux-dev-fp8", device="cpu" if offload else device)
  File "E:\project\deforum-x-flux\./x-flux\src\flux\util.py", line 302, in load_flow_model_quintized
    requantize(model, sd, quantization_map, device=device)
  File "G:\conda\envs_dirs\deforum_xflux\lib\site-packages\optimum\quanto\quantize.py", line 138, in requantize
    model.to(device)
  File "G:\conda\envs_dirs\deforum_xflux\lib\site-packages\torch\nn\modules\module.py", line 1174, in to
    return self._apply(convert)
  File "G:\conda\envs_dirs\deforum_xflux\lib\site-packages\torch\nn\modules\module.py", line 780, in _apply
    module._apply(fn)
  File "G:\conda\envs_dirs\deforum_xflux\lib\site-packages\torch\nn\modules\module.py", line 780, in _apply
    module._apply(fn)
  File "G:\conda\envs_dirs\deforum_xflux\lib\site-packages\torch\nn\modules\module.py", line 780, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "G:\conda\envs_dirs\deforum_xflux\lib\site-packages\torch\nn\modules\module.py", line 805, in _apply
    param_applied = fn(param)
  File "G:\conda\envs_dirs\deforum_xflux\lib\site-packages\torch\nn\modules\module.py", line 1160, in convert
    return t.to(
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 54.00 MiB. GPU 0 has a total capacity of 23.99 GiB of which 0 bytes is free. Of the allocated memory 23.01 GiB is allocated by PyTorch, and 5.82 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```
